name: Determine build version
description: Determines the proper build version using PaulHatch/semantic-version
author: Nichals Hoberg

on:
	workflow_call:
		outputs:
      	version:
        	value: ${{ jobs.determine.outputs.version }}
      	version_tag:
        	value: ${{ jobs.determine.outputs.version_tag }}

jobs:
  	determine:
    	runs-on: ubuntu-latest
    	outputs:
      		version: ${{ steps.set_version.outputs.version }}
      		version_tag: ${{ steps.semver.outputs.version_tag }}
    	steps:
      	-	uses: actions/checkout@v4
			with:
          		fetch-depth: 0

      - 	name: Generate Semantic Version
        	id: semver
        	uses: PaulHatch/semantic-version@v5.4.0
        	with:
          		tag_prefix: "v"
          		major_pattern: "major:"
          		minor_pattern: "minor:"
          		version_format: "${major}.${minor}.${patch}"
          
      - 	name: Set version output
        	id: set_version
        	run: |
          		if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            		echo "version=${{ steps.semver.outputs.version }}" >> $GITHUB_OUTPUT
          		else
            		RC_VERSION="${{ steps.semver.outputs.version }}-rc${{ steps.semver.outputs.increment }}"
            		BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
            		FORMATTED_BRANCH=$(echo $BRANCH_NAME | sed 's/\//-/g')
            		echo "version=${RC_VERSION}-${FORMATTED_BRANCH}" >> $GITHUB_OUTPUT
          		fi